
services:
  - type: web
    name: nuri-piknik-v41
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install gunicorn eventlet
    startCommand: gunicorn -k eventlet -w 1 app.server:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAX_USERS
        value: "50"
      - key: SECRET_KEY
        generateValue: true
