services:
  - type: web
    name: piknik-vakti
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT app.server:app"
    plan: free
    autoDeploy: true
